services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/public/uploads
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./server/instance:/app/instance